FROM mcr.microsoft.com/dotnet/sdk:10.0-preview AS build
ARG PROJECT_PATH
WORKDIR /src
COPY . .
RUN dotnet restore ${PROJECT_PATH}
RUN dotnet publish ${PROJECT_PATH} -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:10.0-preview AS base
WORKDIR /app
COPY --from=build /app/publish .
ARG DLL_NAME
ENV APP_DLL=$DLL_NAME
ENTRYPOINT dotnet ${APP_DLL}
