global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Threading;
global using System.Threading.Tasks;
global using MediatR;
global using FluentValidation;
global using NexusMail.Shared.Common;
global using NexusMail.Application.Abstractions.Messaging;
